### ISSUE TITLE
Bound values collision when preg-replaced without limit.

### ISSUE THREAD

**Issue by vlkolak** [objective-php/mysql-gateway#5]
Hi all,

In a case where a bound value is followed by a second bound value which starts by the first one, the current limitless preg-replacement will cause an Exception.

Code:
https://github.com/objective-php/mysql-gateway/blob/9cb32972c15fa48e51598960cc40c32f2decaefc/src/AbstractMySqlGateway.php#L201-L203

Exemple:

For bound values keys : 
 - someKey
 - someKeyDetailsReference

Binding will result in a string containing :

        ?,  ?DetailsReference,

Consequence : throwed PrepareException.

Immediate solution, at line 202: 

        $sql = preg_replace(sprintf('/:%s/U', $name), '?', $sql, 1);

**Comment by bcerati** [comment]
Fixed in this PR https://github.com/objective-php/mysql-gateway/pull/4
